const API_BASE_URL = '';

const MAX_VISIBLE_BRANCHES = 10;
const COMMITS_PAGE_SIZE = 50;
const MAX_DIRECTORIES = 200;

export { API_BASE_URL, MAX_VISIBLE_BRANCHES, COMMITS_PAGE_SIZE, MAX_DIRECTORIES };
